# application-dev.yml — Common dev config (ทุก service ที่ profile=dev จะได้)
spring:
  datasource:
    # dev ใช้ H2 หรือ local DB
    url: jdbc:h2:mem:paymentdb
    username: sa
    password:

logging:
  level:
    root: INFO
    com.example: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
